import type { Product, Order, Store, User, DashboardStats, Notification } from '@/types';
import { PRODUCT_IMAGES } from '@/constants/localImages';

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Urban Wear KE',
  email: 'urbanwear@gmail.com',
  phone: '+254 712 345 678',
  avatar: undefined,
};

export const MOCK_STORE: Store = {
  id: 's1',
  name: 'Urban Wear KE',
  description: 'Premium fashion & lifestyle brand based in Nairobi. Authentic products with fast delivery across Kenya.',
  phone: '+254 712 345 678',
  email: 'urbanwear@gmail.com',
  location: 'Westlands, Nairobi',
  verified: true,
  rating: 4.8,
  totalSales: 1247,
  totalRevenue: 3842000,
  joinedDate: '2024-01-15T00:00:00.000Z',
  businessHours: 'Mon-Sat: 8AM - 8PM',
  deliveryRadius: '50km from Nairobi CBD',
  whatsappLinked: true,
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'Classic Boat Shoes',
    description: 'Premium leather boat shoes with hand-stitched details and cushioned insoles. Perfect for casual and semi-formal occasions. Free delivery in Nairobi.',
    price: 6500,
    originalPrice: 8500,
    currency: 'KSh',
    images: [PRODUCT_IMAGES.boatShoes],
    category: 'Footwear',
    stock: 24,
    sku: 'CBS-TAN-42',
    variants: [
      { name: 'Color', options: ['Tan', 'Brown', 'Navy'] },
      { name: 'Size', options: ['40', '41', '42', '43', '44'] },
    ],
    status: 'active',
    shopLink: 'statusseller.app/p/CBS42K',
    views: 1284,
    orders: 47,
    createdAt: '2025-07-01T10:00:00.000Z',
    colorHex: '#C47A3A',
  },
  {
    id: 'p2',
    title: 'Oxford Derby Shoes',
    description: 'Elegant tan leather Oxford derby shoes with a rubber sole. Classic cap-toe design, ideal for business and formal events.',
    price: 7800,
    currency: 'KSh',
    images: [PRODUCT_IMAGES.oxfordShoes],
    category: 'Footwear',
    stock: 8,
    sku: 'OXF-TAN-43',
    variants: [
      { name: 'Color', options: ['Tan', 'Black', 'Burgundy'] },
      { name: 'Size', options: ['40', '41', '42', '43', '44', '45'] },
    ],
    status: 'active',
    shopLink: 'statusseller.app/p/OXF43M',
    views: 892,
    orders: 23,
    createdAt: '2025-07-05T09:00:00.000Z',
    colorHex: '#8B5E3C',
  },
  {
    id: 'p3',
    title: 'Vans Old Skool',
    description: 'Iconic Vans Old Skool skate shoes in classic black/white. Canvas upper with vulcanized sole for ultimate durability and style.',
    price: 5500,
    originalPrice: 6500,
    currency: 'KSh',
    images: [PRODUCT_IMAGES.vansSneakers],
    category: 'Footwear',
    stock: 15,
    sku: 'VANS-BLK-42',
    variants: [{ name: 'Size', options: ['38', '39', '40', '41', '42', '43', '44'] }],
    status: 'active',
    shopLink: 'statusseller.app/p/VANS42',
    views: 567,
    orders: 31,
    createdAt: '2025-07-08T14:00:00.000Z',
    colorHex: '#1A1A1A',
  },
  {
    id: 'p4',
    title: 'Pearl Ankle Strap Flats',
    description: 'Elegant nude suede flats featuring a triple-strand pearl ankle strap and satin bow. Perfect for weddings, parties, and special occasions.',
    price: 4500,
    currency: 'KSh',
    images: [PRODUCT_IMAGES.pearlFlats],
    category: 'Footwear',
    stock: 0,
    sku: 'PAF-NUD-38',
    variants: [
      { name: 'Size', options: ['36', '37', '38', '39', '40'] },
    ],
    status: 'out_of_stock',
    shopLink: 'statusseller.app/p/PAF38X',
    views: 341,
    orders: 18,
    createdAt: '2025-06-20T11:00:00.000Z',
    colorHex: '#D4B896',
  },
  {
    id: 'p5',
    title: 'Elegant Black Maxi Dress',
    description: 'Sophisticated long-sleeve black maxi dress with a square neckline and gold-buckle waist detail. Premium stretch fabric, perfect for events.',
    price: 12500,
    currency: 'KSh',
    images: [PRODUCT_IMAGES.blackDress],
    category: 'Clothing',
    stock: 5,
    sku: 'BKD-S-ML',
    variants: [
      { name: 'Size', options: ['XS', 'S', 'M', 'L', 'XL'] },
    ],
    status: 'active',
    shopLink: 'statusseller.app/p/BKD01',
    views: 2100,
    orders: 68,
    createdAt: '2025-07-26T16:00:00.000Z',
    colorHex: '#1A1A1A',
  },
  {
    id: 'p6',
    title: 'Casual Lifestyle Collection',
    description: 'Curated urban lifestyle wear for the modern Kenyan. Comfortable, stylish, and built for everyday life.',
    price: 3500,
    originalPrice: 5000,
    currency: 'KSh',
    images: [PRODUCT_IMAGES.fashion1, PRODUCT_IMAGES.fashion2],
    category: 'Clothing',
    stock: 12,
    sku: 'CLC-M-BLK',
    variants: [
      { name: 'Size', options: ['S', 'M', 'L', 'XL', 'XXL'] },
    ],
    status: 'active',
    shopLink: 'statusseller.app/p/CLC01K',
    views: 890,
    orders: 34,
    createdAt: '2025-07-10T08:00:00.000Z',
    colorHex: '#2D2D2D',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'o1',
    orderNumber: '#SS782310',
    customer: { name: 'John Ochieng', phone: '+254 712 345 678', address: '123 City Road, Nairobi, Kenya' },
    items: [{ productId: 'p1', productTitle: 'Classic Boat Shoes', productImage: '', quantity: 1, price: 6500, variant: 'Size 42 - Tan', colorHex: '#C47A3A' }],
    subtotal: 6500,
    deliveryFee: 200,
    total: 6700,
    currency: 'KSh',
    status: 'delivered',
    paymentMethod: 'M-Pesa',
    paymentStatus: 'paid',
    createdAt: '2025-07-26T14:30:00.000Z',
    updatedAt: '2025-07-27T09:00:00.000Z',
    trackingNumber: 'SS-TRK-38291',
  },
  {
    id: 'o2',
    orderNumber: '#SS782309',
    customer: { name: 'Amina Hassan', phone: '+254 798 123 456', address: '45 Westlands Ave, Nairobi' },
    items: [
      { productId: 'p2', productTitle: 'Oxford Derby Shoes', productImage: '', quantity: 1, price: 7800, variant: 'Size 43 - Tan', colorHex: '#8B5E3C' },
      { productId: 'p5', productTitle: 'Elegant Black Maxi Dress', productImage: '', quantity: 1, price: 12500, variant: 'M', colorHex: '#1A1A1A' },
    ],
    subtotal: 20300,
    deliveryFee: 300,
    total: 20600,
    currency: 'KSh',
    status: 'processing',
    paymentMethod: 'Card',
    paymentStatus: 'paid',
    createdAt: '2025-07-27T08:15:00.000Z',
    updatedAt: '2025-07-27T08:15:00.000Z',
  },
  {
    id: 'o3',
    orderNumber: '#SS782308',
    customer: { name: 'Peter Kamau', phone: '+254 722 987 654', address: 'Kisumu Town, Kisumu' },
    items: [{ productId: 'p3', productTitle: 'Vans Old Skool', productImage: '', quantity: 2, price: 5500, variant: 'Size 43', colorHex: '#1A1A1A' }],
    subtotal: 11000,
    deliveryFee: 500,
    total: 11500,
    currency: 'KSh',
    status: 'shipped',
    paymentMethod: 'M-Pesa',
    paymentStatus: 'paid',
    createdAt: '2025-07-26T20:00:00.000Z',
    updatedAt: '2025-07-27T06:00:00.000Z',
    trackingNumber: 'SS-TRK-38290',
  },
  {
    id: 'o4',
    orderNumber: '#SS782307',
    customer: { name: 'Grace Wanjiru', phone: '+254 733 456 789', address: 'Kiambu Road, Nairobi' },
    items: [{ productId: 'p4', productTitle: 'Pearl Ankle Strap Flats', productImage: '', quantity: 1, price: 4500, variant: 'Size 38', colorHex: '#D4B896' }],
    subtotal: 4500,
    deliveryFee: 200,
    total: 4700,
    currency: 'KSh',
    status: 'pending',
    paymentMethod: 'M-Pesa',
    paymentStatus: 'pending',
    createdAt: '2025-07-27T10:45:00.000Z',
    updatedAt: '2025-07-27T10:45:00.000Z',
  },
  {
    id: 'o5',
    orderNumber: '#SS782306',
    customer: { name: 'Brian Otieno', phone: '+254 710 321 654', address: 'Mombasa Road, Nairobi' },
    items: [{ productId: 'p5', productTitle: 'Elegant Black Maxi Dress', productImage: '', quantity: 1, price: 12500, variant: 'L', colorHex: '#1A1A1A' }],
    subtotal: 12500,
    deliveryFee: 200,
    total: 12700,
    currency: 'KSh',
    status: 'accepted',
    paymentMethod: 'Card',
    paymentStatus: 'paid',
    createdAt: '2025-07-27T09:30:00.000Z',
    updatedAt: '2025-07-27T09:32:00.000Z',
  },
];

export const MOCK_STATS: DashboardStats = {
  todayRevenue: 51700,
  weekRevenue: [28000, 45000, 32000, 67000, 51000, 43000, 51700],
  todayOrders: 4,
  totalProducts: 6,
  activeLinks: 3,
  aiConversations: 12,
  linkClicks: 248,
  conversionRate: 8.4,
  currency: 'KSh',
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', type: 'order', title: 'New Order!', body: 'Grace Wanjiru ordered Pearl Ankle Strap Flats', read: false, createdAt: '2025-07-27T10:45:00.000Z' },
  { id: 'n2', type: 'payment', title: 'Payment Received', body: 'KSh 20,600 from Amina Hassan', read: false, createdAt: '2025-07-27T08:20:00.000Z' },
  { id: 'n3', type: 'message', title: 'New Message', body: 'Customer asking about shoe sizes', read: true, createdAt: '2025-07-27T07:30:00.000Z' },
];

export const AI_RESPONSES: Record<string, string> = {
  default: "I'm your AI Sales Agent. I can help answer customer questions about your products, pricing, and delivery. How can I assist you today?",
  sizes: "Based on your product catalog, Classic Boat Shoes are available in sizes 40-44. Oxford Derby Shoes come in 40-45. Vans Old Skool in 38-44.",
  delivery: "You offer delivery across Kenya. Standard delivery to Nairobi takes 1-2 days (KSh 200), upcountry takes 2-3 days (KSh 300-500).",
  payment: "You accept M-Pesa, Visa, Mastercard, and Cash on Delivery. M-Pesa is the most popular payment method among your customers.",
  stock: "Classic Boat Shoes: 24 units. Oxford Derby Shoes: 8 units. Vans Old Skool: 15 units. Pearl Ankle Strap Flats are currently out of stock.",
  returns: "Your return policy: items can be returned within 7 days of delivery if in original condition. Refunds processed within 3-5 business days.",
};

export const PRODUCT_CATEGORIES = ['All', 'Footwear', 'Clothing', 'Accessories', 'Beauty', 'Home', 'Electronics'];

export const BUTTON_STYLES = [
  { id: 'shop_now', label: 'Shop Now', icon: 'cart-outline' },
  { id: 'buy_now', label: 'Buy Now', icon: 'flash-outline' },
  { id: 'view_product', label: 'View Product', icon: 'eye-outline' },
  { id: 'ask_ai', label: 'Ask AI', icon: 'chatbubble-outline' },
  { id: 'add_to_cart', label: 'Add to Cart', icon: 'bag-add-outline' },
];
