import type { Product, Order, Store, User, DashboardStats, Notification } from '@/types';

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Urban Wear KE',
  email: 'urbanwear@gmail.com',
  phone: '+254 712 345 678',
  avatar: undefined,
};

export const MOCK_STORE: Store = {
  id: 's1',
  name: 'Urban Wear KE',
  description: 'Premium fashion & lifestyle brand based in Nairobi. Authentic products with fast delivery across Kenya.',
  phone: '+254 712 345 678',
  email: 'urbanwear@gmail.com',
  location: 'Westlands, Nairobi',
  verified: true,
  rating: 4.8,
  totalSales: 1247,
  totalRevenue: 3842000,
  joinedDate: '2024-01-15T00:00:00.000Z',
  businessHours: 'Mon-Sat: 8AM - 8PM',
  deliveryRadius: '50km from Nairobi CBD',
  whatsappLinked: true,
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'Nike Air Force 1',
    description: '100% original Nike Air Force 1 sneakers with official warranty. Available in multiple sizes.',
    price: 6000,
    originalPrice: 8500,
    currency: 'KSh',
    images: [],
    category: 'Footwear',
    stock: 24,
    sku: 'NAF1-WHT-42',
    variants: [{ name: 'Size', options: ['40', '41', '42', '43', '44'] }],
    status: 'active',
    shopLink: 'statusseller.app/p/ABX92K',
    views: 1284,
    orders: 47,
    createdAt: '2025-07-01T10:00:00.000Z',
    colorHex: '#E5E5E5',
  },
  {
    id: 'p2',
    title: 'Samsung Galaxy Watch 6',
    description: 'Samsung Galaxy Watch 6 44mm - Black. Smart fitness tracking, health monitoring, and more.',
    price: 28000,
    currency: 'KSh',
    images: [],
    category: 'Electronics',
    stock: 8,
    sku: 'SGW6-44-BLK',
    variants: [
      { name: 'Color', options: ['Black', 'Silver'] },
      { name: 'Size', options: ['40mm', '44mm'] },
    ],
    status: 'active',
    shopLink: 'statusseller.app/p/GWX44M',
    views: 892,
    orders: 23,
    createdAt: '2025-07-05T09:00:00.000Z',
    colorHex: '#1A1A2E',
  },
  {
    id: 'p3',
    title: 'JBL Tune 510BT',
    description: 'JBL Tune 510BT wireless headphones. 40hr battery life, Pure Bass sound.',
    price: 5000,
    originalPrice: 6500,
    currency: 'KSh',
    images: [],
    category: 'Electronics',
    stock: 15,
    sku: 'JBL-T510-BLK',
    variants: [{ name: 'Color', options: ['Black', 'Blue', 'Pink'] }],
    status: 'active',
    shopLink: 'statusseller.app/p/JBL510',
    views: 567,
    orders: 31,
    createdAt: '2025-07-08T14:00:00.000Z',
    colorHex: '#1A1A2E',
  },
  {
    id: 'p4',
    title: 'Levi\'s 501 Jeans',
    description: 'Classic Levi\'s 501 original fit jeans. Timeless American style.',
    price: 4500,
    currency: 'KSh',
    images: [],
    category: 'Clothing',
    stock: 0,
    sku: 'LV501-32-BLU',
    variants: [
      { name: 'Size', options: ['28', '30', '32', '34', '36'] },
      { name: 'Wash', options: ['Light', 'Medium', 'Dark'] },
    ],
    status: 'out_of_stock',
    shopLink: 'statusseller.app/p/LV501X',
    views: 341,
    orders: 18,
    createdAt: '2025-06-20T11:00:00.000Z',
    colorHex: '#1D3A6B',
  },
  {
    id: 'p5',
    title: 'Apple AirPods Pro 2',
    description: 'Apple AirPods Pro 2nd Generation with Active Noise Cancellation.',
    price: 18500,
    currency: 'KSh',
    images: [],
    category: 'Electronics',
    stock: 5,
    sku: 'APP2-WHT',
    variants: [],
    status: 'draft',
    shopLink: 'statusseller.app/p/APP2KE',
    views: 0,
    orders: 0,
    createdAt: '2025-07-26T16:00:00.000Z',
    colorHex: '#F5F5F5',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'o1',
    orderNumber: '#SS782310',
    customer: { name: 'John Ochieng', phone: '+254 712 345 678', address: '123 City Road, Nairobi, Kenya' },
    items: [{ productId: 'p1', productTitle: 'Nike Air Force 1', productImage: '', quantity: 1, price: 6000, variant: 'Size 42 - White', colorHex: '#E5E5E5' }],
    subtotal: 6000,
    deliveryFee: 200,
    total: 6200,
    currency: 'KSh',
    status: 'delivered',
    paymentMethod: 'M-Pesa',
    paymentStatus: 'paid',
    createdAt: '2025-07-26T14:30:00.000Z',
    updatedAt: '2025-07-27T09:00:00.000Z',
    trackingNumber: 'SS-TRK-38291',
  },
  {
    id: 'o2',
    orderNumber: '#SS782309',
    customer: { name: 'Amina Hassan', phone: '+254 798 123 456', address: '45 Westlands Ave, Nairobi' },
    items: [
      { productId: 'p2', productTitle: 'Samsung Galaxy Watch 6', productImage: '', quantity: 1, price: 28000, variant: '44mm - Black', colorHex: '#1A1A2E' },
      { productId: 'p3', productTitle: 'JBL Tune 510BT', productImage: '', quantity: 1, price: 5000, variant: 'Black', colorHex: '#1A1A2E' },
    ],
    subtotal: 33000,
    deliveryFee: 300,
    total: 33300,
    currency: 'KSh',
    status: 'processing',
    paymentMethod: 'Card',
    paymentStatus: 'paid',
    createdAt: '2025-07-27T08:15:00.000Z',
    updatedAt: '2025-07-27T08:15:00.000Z',
  },
  {
    id: 'o3',
    orderNumber: '#SS782308',
    customer: { name: 'Peter Kamau', phone: '+254 722 987 654', address: 'Kisumu Town, Kisumu' },
    items: [{ productId: 'p1', productTitle: 'Nike Air Force 1', productImage: '', quantity: 2, price: 6000, variant: 'Size 43', colorHex: '#E5E5E5' }],
    subtotal: 12000,
    deliveryFee: 500,
    total: 12500,
    currency: 'KSh',
    status: 'shipped',
    paymentMethod: 'M-Pesa',
    paymentStatus: 'paid',
    createdAt: '2025-07-26T20:00:00.000Z',
    updatedAt: '2025-07-27T06:00:00.000Z',
    trackingNumber: 'SS-TRK-38290',
  },
  {
    id: 'o4',
    orderNumber: '#SS782307',
    customer: { name: 'Grace Wanjiru', phone: '+254 733 456 789', address: 'Kiambu Road, Nairobi' },
    items: [{ productId: 'p3', productTitle: 'JBL Tune 510BT', productImage: '', quantity: 1, price: 5000, variant: 'Blue', colorHex: '#1D3A6B' }],
    subtotal: 5000,
    deliveryFee: 200,
    total: 5200,
    currency: 'KSh',
    status: 'pending',
    paymentMethod: 'M-Pesa',
    paymentStatus: 'pending',
    createdAt: '2025-07-27T10:45:00.000Z',
    updatedAt: '2025-07-27T10:45:00.000Z',
  },
  {
    id: 'o5',
    orderNumber: '#SS782306',
    customer: { name: 'Brian Otieno', phone: '+254 710 321 654', address: 'Mombasa Road, Nairobi' },
    items: [{ productId: 'p2', productTitle: 'Samsung Galaxy Watch 6', productImage: '', quantity: 1, price: 28000, variant: '40mm - Silver', colorHex: '#C0C0C0' }],
    subtotal: 28000,
    deliveryFee: 200,
    total: 28200,
    currency: 'KSh',
    status: 'accepted',
    paymentMethod: 'Card',
    paymentStatus: 'paid',
    createdAt: '2025-07-27T09:30:00.000Z',
    updatedAt: '2025-07-27T09:32:00.000Z',
  },
];

export const MOCK_STATS: DashboardStats = {
  todayRevenue: 51700,
  weekRevenue: [28000, 45000, 32000, 67000, 51000, 43000, 51700],
  todayOrders: 4,
  totalProducts: 5,
  activeLinks: 3,
  aiConversations: 12,
  linkClicks: 248,
  conversionRate: 8.4,
  currency: 'KSh',
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', type: 'order', title: 'New Order!', body: 'Grace Wanjiru ordered JBL Tune 510BT', read: false, createdAt: '2025-07-27T10:45:00.000Z' },
  { id: 'n2', type: 'payment', title: 'Payment Received', body: 'KSh 33,300 from Amina Hassan', read: false, createdAt: '2025-07-27T08:20:00.000Z' },
  { id: 'n3', type: 'message', title: 'AI Conversation', body: 'Customer asking about Nike sizes', read: true, createdAt: '2025-07-27T07:30:00.000Z' },
];

export const AI_RESPONSES: Record<string, string> = {
  default: "I'm your AI Sales Agent. I can help answer customer questions about your products, pricing, and delivery. How can I assist you today?",
  sizes: "Based on your product catalog, the Nike Air Force 1 is available in sizes 40-44. The Samsung Galaxy Watch 6 comes in 40mm and 44mm case sizes.",
  delivery: "You offer delivery across Kenya. Standard delivery to Nairobi takes 1-2 days (KSh 200), upcountry takes 2-3 days (KSh 300-500).",
  payment: "You accept M-Pesa, Visa, Mastercard, and Cash on Delivery. M-Pesa is the most popular payment method among your customers.",
  stock: "The Nike Air Force 1 has 24 units in stock. Samsung Galaxy Watch 6 has 8 units. JBL Tune 510BT has 15 units. Levi's 501 Jeans are currently out of stock.",
  returns: "Your return policy: items can be returned within 7 days of delivery if in original condition. Refunds processed within 3-5 business days.",
};

export const PRODUCT_CATEGORIES = ['All', 'Footwear', 'Electronics', 'Clothing', 'Accessories', 'Beauty', 'Home'];

export const BUTTON_STYLES = [
  { id: 'shop_now', label: 'Shop Now', icon: 'cart-outline' },
  { id: 'buy_now', label: 'Buy Now', icon: 'flash-outline' },
  { id: 'view_product', label: 'View Product', icon: 'eye-outline' },
  { id: 'ask_ai', label: 'Ask AI', icon: 'chatbubble-outline' },
  { id: 'add_to_cart', label: 'Add to Cart', icon: 'bag-add-outline' },
];
